modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="infinitemechanism" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Infinite Mechanism" #mandatory
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
#logoFile="examplemod.png" #optional
#credits="Thanks for minecraft." #optional
authors="jihuayu" #optional
description='''
A example mod.
'''
[[dependencies.cuisine]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.cuisine]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
